// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP-QPTIFioyIFjDTDbEGPA7QlGLcISQLk',
    appId: '1:900747740738:web:59df6db015e342506a4fdb',
    messagingSenderId: '900747740738',
    projectId: 'quizapp-b7db2',
    authDomain: 'quizapp-b7db2.firebaseapp.com',
    storageBucket: 'quizapp-b7db2.appspot.com',
    measurementId: 'G-TYZ2X9QR56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqJQp7Z08kpw7KACTMX_y__Xycy2naCp0',
    appId: '1:900747740738:android:d2ec627d9522aadf6a4fdb',
    messagingSenderId: '900747740738',
    projectId: 'quizapp-b7db2',
    storageBucket: 'quizapp-b7db2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAH6rCqCdv96xyFu8PVFsKjx7EX3wjnIs',
    appId: '1:900747740738:ios:8a64ebbfadecb5df6a4fdb',
    messagingSenderId: '900747740738',
    projectId: 'quizapp-b7db2',
    storageBucket: 'quizapp-b7db2.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAH6rCqCdv96xyFu8PVFsKjx7EX3wjnIs',
    appId: '1:900747740738:ios:8a64ebbfadecb5df6a4fdb',
    messagingSenderId: '900747740738',
    projectId: 'quizapp-b7db2',
    storageBucket: 'quizapp-b7db2.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP-QPTIFioyIFjDTDbEGPA7QlGLcISQLk',
    appId: '1:900747740738:web:4fd6b6b19a0c511c6a4fdb',
    messagingSenderId: '900747740738',
    projectId: 'quizapp-b7db2',
    authDomain: 'quizapp-b7db2.firebaseapp.com',
    storageBucket: 'quizapp-b7db2.appspot.com',
    measurementId: 'G-ZYCJJD8ENK',
  );
}
